/APPs/fsl/bin/run_first -i T1 -t T1_to_std_sub.mat -n 50 -o first-L_Accu_first -m /APPs/fsl/data/first/models_336_bin/L_Accu_bin.bmv; /APPs/fsl/bin/first_boundary_corr -s first-L_Accu_first -o first-L_Accu_corr -i T1 -b none
/APPs/fsl/bin/run_first -i T1 -t T1_to_std_sub.mat -n 50 -o first-R_Accu_first -m /APPs/fsl/data/first/models_336_bin/R_Accu_bin.bmv; /APPs/fsl/bin/first_boundary_corr -s first-R_Accu_first -o first-R_Accu_corr -i T1 -b none
/APPs/fsl/bin/run_first -i T1 -t T1_to_std_sub.mat -n 30 -o first-L_Caud_first -m /APPs/fsl/data/first/models_336_bin/intref_thal/L_Caud.bmv -intref /APPs/fsl/data/first/models_336_bin/05mm/L_Thal_05mm.bmv; /APPs/fsl/bin/first_boundary_corr -s first-L_Caud_first -o first-L_Caud_corr -i T1 -b none
/APPs/fsl/bin/run_first -i T1 -t T1_to_std_sub.mat -n 30 -o first-R_Caud_first -m /APPs/fsl/data/first/models_336_bin/intref_thal/R_Caud.bmv -intref /APPs/fsl/data/first/models_336_bin/05mm/R_Thal_05mm.bmv; /APPs/fsl/bin/first_boundary_corr -s first-R_Caud_first -o first-R_Caud_corr -i T1 -b none
/APPs/fsl/bin/run_first -i T1 -t T1_to_std_sub.mat -n 40 -o first-L_Pall_first -m /APPs/fsl/data/first/models_336_bin/05mm/L_Pall_05mm.bmv; /APPs/fsl/bin/first_boundary_corr -s first-L_Pall_first -o first-L_Pall_corr -i T1 -b none
/APPs/fsl/bin/run_first -i T1 -t T1_to_std_sub.mat -n 40 -o first-R_Pall_first -m /APPs/fsl/data/first/models_336_bin/05mm/R_Pall_05mm.bmv; /APPs/fsl/bin/first_boundary_corr -s first-R_Pall_first -o first-R_Pall_corr -i T1 -b none
/APPs/fsl/bin/run_first -i T1 -t T1_to_std_sub.mat -n 40 -o first-L_Puta_first -m /APPs/fsl/data/first/models_336_bin/05mm/L_Puta_05mm.bmv; /APPs/fsl/bin/first_boundary_corr -s first-L_Puta_first -o first-L_Puta_corr -i T1 -b none
/APPs/fsl/bin/run_first -i T1 -t T1_to_std_sub.mat -n 40 -o first-R_Puta_first -m /APPs/fsl/data/first/models_336_bin/05mm/R_Puta_05mm.bmv; /APPs/fsl/bin/first_boundary_corr -s first-R_Puta_first -o first-R_Puta_corr -i T1 -b none
/APPs/fsl/bin/run_first -i T1 -t T1_to_std_sub.mat -n 40 -o first-L_Thal_first -m /APPs/fsl/data/first/models_336_bin/05mm/L_Thal_05mm.bmv; /APPs/fsl/bin/first_boundary_corr -s first-L_Thal_first -o first-L_Thal_corr -i T1 -b none
/APPs/fsl/bin/run_first -i T1 -t T1_to_std_sub.mat -n 40 -o first-R_Thal_first -m /APPs/fsl/data/first/models_336_bin/05mm/R_Thal_05mm.bmv; /APPs/fsl/bin/first_boundary_corr -s first-R_Thal_first -o first-R_Thal_corr -i T1 -b none
